apiVersion: v1
kind: ConfigMap
metadata:
  name: veg-config
  namespace: bhagwat-ns
data:
  MONGO_URI: "mongodb://mongodb-svc:27017/vegetable_order_app"
  MONGO_INITDB_DATABASE: "vegetable_order_app"
